add_action('wp_head', function () {
    if (!is_front_page()) { return; }
    echo '<script type="application/ld+json">' . '{"@context": "https://schema.org", "@type": "FAQPage", "@id": "https://rooval-roofing.com/#faq", "mainEntity": [{"@type": "Question", "name": "How do I know if my roof needs to be replaced?", "acceptedAnswer": {"@type": "Answer", "text": "If your roof is over 15\u201320 years old, has missing shingles, leaks, or visible sagging, it may be time for a replacement. Our experts can inspect your roof and recommend whether repair or replacement is the best solution."}}, {"@type": "Question", "name": "How long does a roof replacement take?", "acceptedAnswer": {"@type": "Answer", "text": "Most residential roof replacements are completed in 1\u20132 days, depending on roof size, weather conditions, and material type. We always aim to minimize disruption to your home."}}, {"@type": "Question", "name": "What types of roofing materials do you offer?", "acceptedAnswer": {"@type": "Answer", "text": "We install a variety of roofing materials, including asphalt shingles, metal roofing, tile, and flat roofing systems \u2014 all sourced from trusted manufacturers for long-lasting performance."}}, {"@type": "Question", "name": "Do you inspect for storm, wind, and hail damage?", "acceptedAnswer": {"@type": "Answer", "text": "Yes. After a storm we\u2019ll inspect your roof and document any wind or hail damage with clear photos and a written report, then walk you through the claims paperwork so nothing gets missed. You file the claim with your insurer, and our documentation backs you up every step of the way."}}, {"@type": "Question", "name": "Do you offer free roof inspections or estimates?", "acceptedAnswer": {"@type": "Answer", "text": "Yes, we offer free, no-obligation roof inspections and quotes. Our team will assess your roof\u2019s condition and provide a detailed estimate before any work begins."}}]}' . '</script>';
}, 15);

add_filter('the_content', function ($content) {
    if (!is_front_page() || !in_the_loop() || !is_main_query()) { return $content; }
    if (strpos($content, 'rr-answer-block') !== false) { return $content; }
    $block = '<div class="rr-answer-block" style="max-width:1140px;margin:0 auto;padding:18px 20px 4px"><p style="font-size:1.06em;line-height:1.6">Rooval Roofing repairs and replaces roofs &#8212; including metal and TPO flat roofing &#8212; plus gutters, for homeowners in Lehi, Utah County, and the Salt Lake Valley. Every job starts with a free inspection and a written quote, backed by our workmanship warranty.</p></div>';
    return $block . $content;
}, 15);